import type { Metadata } from "next";
import Link from "next/link";
import { currentAccount } from "@/lib/auth-session";
import { PublicNav, PublicFooter } from "@/components/site/PublicChrome";
import "../legal.css";

// Public, no-login route (Twilio/A2P + general privacy compliance). Never
// gated behind requireAccount — currentAccount() here only decides whether
// the nav shows "Sign In" or "Enter your Space," same as the About page.
export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "Privacy Policy — Magical Moments by Reign",
  description: "How Magical Moments by Reign collects, uses, and protects your personal information, including phone number and SMS messaging data.",
};

const LAST_UPDATED = "August 23, 2026";

export default async function PrivacyPolicyPage() {
  const signedIn = Boolean(await currentAccount());
  return (
    <div className="legal-page">
      <PublicNav active={null} signedIn={signedIn} />
      <div className="legal-wrap">
        <span className="legal-eyebrow">Legal</span>
        <h1 className="legal-title">Privacy Policy</h1>
        <p className="legal-updated">Last updated: {LAST_UPDATED}</p>

        <div className="legal-toc">
          <b>On this page</b>
          <ol>
            <li><a href="#who-we-are">Who we are</a></li>
            <li><a href="#info-we-collect">Information we collect</a></li>
            <li><a href="#sms">Phone numbers &amp; SMS/text messaging</a></li>
            <li><a href="#how-we-use">How we use your information</a></li>
            <li><a href="#sharing">How we share information</a></li>
            <li><a href="#security">Security &amp; data retention</a></li>
            <li><a href="#rights">Your rights &amp; choices</a></li>
            <li><a href="#contact">Contact us</a></li>
          </ol>
        </div>

        <h2 id="who-we-are">1. Who we are</h2>
        <p>
          This Privacy Policy is issued by <strong>Magical Moments by Reign</strong> (&ldquo;Magical Moments,&rdquo;
          &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), the operator of the website and platform at{" "}
          <a href="https://magicalmomentsbyreign.com">magicalmomentsbyreign.com</a> and the associated Magical
          Moments dashboard, mobile experiences, and communications (together, the &ldquo;Service&rdquo;). This
          policy explains what personal information we collect, how we use and share it, and the choices you have.
        </p>
        <p>
          Business mailing address: 1 Perimeter Park South, Birmingham, AL 35243.
          Contact: <a href="mailto:info@magicalmomentsbyreign.com">info@magicalmomentsbyreign.com</a>.
        </p>

        <h2 id="info-we-collect">2. Information we collect</h2>
        <p>We collect information you provide directly, information generated by your use of the Service, and information about the people you invite or communicate with through the Service:</p>
        <ul>
          <li><strong>Account information:</strong> name, email address, password (hashed — we never store it in plain text), date of birth where required for identity or plan verification, and profile details you choose to add.</li>
          <li><strong>Phone number:</strong> if you provide a mobile phone number for your account, two-factor security, or SMS notifications.</li>
          <li><strong>Billing information:</strong> processed by our payment processor; we store limited, non-sensitive billing metadata (never full card numbers) needed to service your membership or purchases.</li>
          <li><strong>Content you create or upload:</strong> occasions, journeys, galleries, guestbook entries, registry items, gift lists, video invitations, family and vault records, messages, and similar content you add to the Service.</li>
          <li><strong>Invitation &amp; contact information:</strong> when you invite a family member, guest, or fantasy-league participant, we collect the email address or phone number you provide for that invitee so we can deliver the invitation.</li>
          <li><strong>Usage &amp; device information:</strong> pages visited, features used, browser/device type, and similar diagnostic information, collected automatically to keep the Service reliable and secure.</li>
          <li><strong>Communications content:</strong> the content of in-app messages, notifications, and support requests you send or receive through the Service.</li>
        </ul>

        <h2 id="sms">3. Phone numbers &amp; SMS/text messaging</h2>
        <div className="legal-callout">
          <p><strong>SMS consent is always optional.</strong> Providing a mobile phone number and opting in to text messages is never required to create an account, make a purchase, or use any paid feature of the Service.</p>
          <p><strong>What SMS is used for.</strong> If you opt in, we (or our SMS delivery provider, acting on our behalf) may text you about: account and login security codes; invitations you send or receive (family, guest, event, video invitation, Fantasy Football league); registry and gift activity; travel, airfare, hotel, and restaurant reservation confirmations and updates arranged through Magical Moments Concierge/Luxury Services; event reminders; and messages from other members sent to you through the Service (e.g., a Fantasy league or family message, when you&rsquo;ve enabled SMS delivery for that notification type).</p>
          <p><strong>Message frequency varies</strong> based on your activity and the notification categories you enable — from a few messages a month to more during an active event, reservation, or fantasy season.</p>
          <p><strong>Message and data rates may apply</strong> from your mobile carrier. Magical Moments does not charge for SMS delivery itself, but standard carrier text/data rates apply to any message sent to your device.</p>
          <p><strong>To stop receiving texts</strong>, reply <strong>STOP</strong> to any message at any time, or turn off SMS in your notification preferences. You&rsquo;ll receive a one-time confirmation that you&rsquo;ve been unsubscribed. <strong>Reply HELP</strong> to any message for assistance, or contact us at <a href="mailto:info@magicalmomentsbyreign.com">info@magicalmomentsbyreign.com</a>.</p>
          <p><strong>Your phone number and SMS opt-in consent are not sold</strong>, and are never shared with third parties or affiliates for their own marketing or promotional purposes. Text messaging originator opt-in data and consent will not be shared with any third party for marketing purposes.</p>
        </div>

        <h2 id="how-we-use">4. How we use your information</h2>
        <p>We use the information above to: operate, maintain, and improve the Service; create and manage your account and membership; deliver the features you use (occasions, journeys, registry, guestbook, video invitations, Family Command Center, Discovery, Magical Picks, Fantasy Football, Luxury Services/Concierge reservations); process invitations you send; send transactional notifications (in-app, email, and — where you&rsquo;ve opted in — SMS) about your account, invitations, reservations, gifts, events, reminders, and messages from other members; provide customer support; detect and prevent fraud and abuse; and comply with legal obligations.</p>

        <h2 id="sharing">5. How we share information</h2>
        <p>We do not sell your personal information, and we do not sell or rent your phone number or SMS consent to anyone. We share information only as follows:</p>
        <ul>
          <li><strong>Service providers,</strong> who process data solely to provide the requested service on our behalf and under contractual confidentiality obligations — for example, our email delivery provider (for account, invitation, and notification emails), our SMS delivery provider (for text messages you&rsquo;ve opted into), our payment processor (for billing), and providers of the live sports, travel, and reservation data that power specific features you use.</li>
          <li><strong>People you choose to interact with,</strong> such as a family member, guest, or fantasy-league participant you invite, who will see the information necessary for that invitation or shared activity (e.g., your name and the league or event you invited them to).</li>
          <li><strong>Legal &amp; safety reasons,</strong> where required by law, to protect the rights and safety of our members and the public, or to enforce our Terms.</li>
          <li><strong>Business transfers,</strong> in the event of a merger, acquisition, or sale of assets, subject to this Privacy Policy continuing to apply to your information.</li>
        </ul>
        <p>Mobile information — including phone numbers and SMS opt-in status — is <strong>never shared with third parties or affiliates for marketing or promotional purposes</strong>, under any circumstance.</p>

        <h2 id="security">6. Security &amp; data retention</h2>
        <p>We use reasonable administrative, technical, and physical safeguards designed to protect your personal information, including encrypted password storage and access controls limiting who at Magical Moments can view member data. No method of transmission or storage is 100% secure, and we cannot guarantee absolute security.</p>
        <p>We retain personal information for as long as your account is active or as needed to provide the Service, comply with legal obligations, resolve disputes, and enforce our agreements. You may request deletion of your account and associated personal information at any time, subject to information we&rsquo;re required to retain by law.</p>

        <h2 id="rights">7. Your rights &amp; choices</h2>
        <p>You can review and update your account information, and manage your in-app, email, and SMS notification preferences by category, at any time from your account settings. Depending on where you live, you may have additional rights to access, correct, delete, or export your personal information, or to object to certain processing. To exercise any of these rights, contact us using the information below.</p>

        <h2 id="contact">8. Contact us</h2>
        <p>Questions about this Privacy Policy or your personal information can be sent to <a href="mailto:info@magicalmomentsbyreign.com">info@magicalmomentsbyreign.com</a>.</p>
        <p>See also our <Link href="/terms">Terms of Service</Link>.</p>
      </div>
      <PublicFooter year={new Date().getFullYear()} />
    </div>
  );
}
